import type { Metadata } from "next"
import { Jost, Poppins } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import { cn } from "@/lib/utils"

// Assign unique variables to each font
const jost = Jost({ subsets: ["latin"], variable: "--font-jost" })
const poppins = Poppins({ 
  subsets: ["latin"], 
  variable: "--font-poppins", 
  display: "swap", 
  weight: ["400", "500", "700"]  // Include desired font weights here
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          jost.variable,  // Use the Jost font variable
          poppins.variable  // Use the Poppins font variable
        )}
      >
        {children}
        <Toaster /> 
      </body>
    </html>
  )
}
