import type { Metadata } from "next"
import { Jost, Poppins } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import { cn } from "@/lib/utils"
import {ClerkProvider} from "@clerk/nextjs"
// Assign unique variables to each font
const jost = Jost({ subsets: ["latin"], variable: "--font-jost" })
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["400", "500", "700"]  // Include desired font weights here
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/fav.ico",                   
    shortcut: "/fav.ico",              
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="\public/fav.ico" type="image/x-icon" />
        </head>
        <body
          className={cn(
            "bg-background min-h-screen font-sans antialiased",
            jost.variable,  // Use the Jost font variable
            poppins.variable  // Use the Poppins font variable
          )}
        >
          {children}
          <Toaster />
        </body>
      </html>
     </ClerkProvider>
  )
}
